---
version: 2.1
jobs:
  test:
    docker:
      - image: girder/girder_test:py39-node14
      - image: mongo:4.4
        command: bash -c "mkdir /dev/shm/mongo && mongod --nojournal --dbpath=/dev/shm/mongo --noauth --bind_ip_all"

    steps:
      - checkout
      - run:
          name: Run server tests
          command: tox

workflows:
  version: 2
  ci:
    jobs:
      - test
  periodic:
    triggers:
      - schedule:
          cron: "0 0 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - test
